### PR TITLE
WL-2106

### PR DESCRIPTION
**Pull request by nicholaswilson100**
Linked to https://github.com/ox-it/wl-reference/pull/68

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
The first commit is a bug fix (that I came across doing this jira).

**Comment by buckett** [comment]
We're still making an extra trip to the server here.
I was meaning to include it in an exsiting file.

**Comment by nicholaswilson100** [comment]
It's separate js functionality which I was thinking deserves its own file.  It gets cached like any other js if performance is the issue.  

I don't mind putting it in an existing file if you think it's a problem (it'd be quick to do :) )...

**Comment by buckett** [comment]
I agree that it's very distinct and separate functionality and it will get
cached but it seems a shame to degrade performance more.

## 

  Matthew Buckett, VLE Developer, IT Services, University of Oxford

**Comment by nicholaswilson100** [comment]
We can monitor it but I don't think it's going to have a large performance impact, and certainly not as much as other things could do like database calls, session sizes, gc, etc. 
Once the concat/minify stuff is in, it'll be even less of a problem.
(your call though, it won't take long to do)

**Pull request merged**
