### PR TITLE
WL-3682 : Change hover over text for buttons in top right

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Linked to https://github.com/ox-it/wl-kernel/pull/56

**Comment by nicholaswilson100** [comment]
This request also comes with a SVN properties commit which would have this:

...
...
xlogin.enabled=true
xlogin.text=Other Users Login
xlogin.text.title=Login for users who have a WebLearn account but do not have an Oxford Single Sign-On account
login.text=Oxford Account Login
login.text.title=Login for users who have an Oxford Single Sign-On account
,,,
,,,

**Comment by nicholaswilson100** [comment]
And a migration script:

https://svn.oucs.ox.ac.uk/projects/vle/deployment/debian/sakai/sql/2559619/

**Comment by buckett** [comment]
Why the need to have the title on the link be different to the alt attribute on the image now?

**Comment by nicholaswilson100** [comment]
Yes they should be the same

**Comment by buckett** [comment]
Doesn't currently merge against sakai-10.x branch.

**Pull request closed without merging**
