### PR TITLE
WL-3665 Don't NPE if Home or Web Content tools

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
At the moment, when you click on a tool in the pda site, if the tool has an entry for 'portlet-context' in its config, it won't create the resetActionUrl (as toolContextPath is null). This change says to create the toolContextPath (and so the resetActionUrl) if the clicked-on tool has the entry or if it's the Home or Web Content tool.

**Comment by buckett** [comment]
Is this issue similar to: https://jira.sakaiproject.org/browse/SAK-26570?

**Comment by nicholaswilson100** [comment]
Yes it is. I'll cherry pick that

**Comment by nicholaswilson100** [comment]
Thanks

**Pull request closed without merging**
