### PR TITLE
WL-3293

### PR DESCRIPTION
**Pull request by nicholaswilson100**
Rename PDA 'Log in' button text to 'Oxford Users'

### CODE REVIEW

**Comment by buckett** [comment]
Is there a reason for not pulling the value from sakai.properties in a similar way to the normal portal?

**Comment by nicholaswilson100** [comment]
We could get it from sakai.properties but at it stands this button text is got from the 'pda_login' property which is not currently in sakai.properties, it's in properties files in the portal submodule.  I could change it to use sakai.properties - it would just mean a bigger change.

**Comment by buckett** [comment]
But why is one of the button's labels coming from sakai.properties, but the other one isn't?
Also this change would never go back into Sakai. Having the pda portal harmonise with the main portal should.

**Comment by nicholaswilson100** [comment]
Good question. Sounds like the best thing to do is put it in sakai.properties like the other one.  As well as getting back to Sakai, it would make it nice and consistent.

**Comment by buckett** [comment]
The value should already by in sakai.properties, it's just a case of
getting it out.

On 27 June 2014 11:27, nicholaswilson100 notifications@github.com wrote:

> Good question. Sounds like the best thing to do is put it in
> sakai.properties like the other one. As well as getting back to Sakai, it
> would make it nice and consistent.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ox-it/wl-portal/pull/9#issuecomment-47329183.

## 

  Matthew Buckett, VLE Developer, IT Services, University of Oxford

**Comment by nicholaswilson100** [comment]
'Oxford Users' is not in sakai.properties as a value so I'll add a new property.

**Comment by buckett** [comment]
Looks good, could you just drop the i18n string if it's unused from the properties file.

**Comment by nicholaswilson100** [comment]
yup I've removed the unused pda_login property from properties files

**Comment by nicholaswilson100** [comment]
By doing this, I meant to merge the Pull requests (as the button said) not merge the code!

**Comment by buckett** [comment]
Re-opened in #10

**Pull request merged**
